app/__init__.py
from flask import Flask
from sassutils.wsgi import SassMiddleware

from config import Config


def create_app(config_class=Config):
    app = Flask(__name__, template_folder="templates")
    app.config.from_object(config_class)
    app.wsgi_app = SassMiddleware(
        app.wsgi_app, {"app": ("static/sass", "static/css", "/static/css")}
    )

    from app.main import bp as main_bp

    app.register_blueprint(main_bp)

    from app.ciphers import bp as ciphers_bp

    app.register_blueprint(ciphers_bp, url_prefix="/ciphers")

    from app.api import bp as api_bp

    app.register_blueprint(api_bp, url_prefix="/api/v1")

    from app.filters import bp as filters_bp

    app.register_blueprint(filters_bp)

    # might move to dedicated file
    # does not work: https://stackoverflow.com/a/5223810
    app.jinja_env.globals.update(zip=zip)

    return app

app/api/__init__.py
from flask import Blueprint

bp = Blueprint("api", __name__)

from app.api.ciphers import hill_cipher, rsa

app/ciphers/__init__.py
from flask import Blueprint

bp = Blueprint("ciphers", __name__)

from app.ciphers import atbash_cipher, caesar_cipher, hill_cipher, rsa, vigenere_cipher

app/hill_cipher/routes.py
from math import isqrt

import numpy as np
import sympy as sp
from flask import Response, jsonify, render_template, request, session

import app.mathutils as mu
from app.hill_cipher import bp
from app.types import ColumnVector, Matrix


@bp.route("/hill-cipher", methods=["GET", "POST"])
def hill_cipher():
    return render_template("ciphers/hill-cipher.html")


@bp.route("/api/hill-cipher", methods=["GET", "POST"])
def hill_cipher_api() -> Response:
    message: str = request.args.get("message", "").strip().upper()
    key: str = request.args.get("key", "").strip().upper()
    keysize: int = request.args.get("keysize", type=int)
    mode: str = request.args.get("mode", "").strip().lower()

    if not key.isalpha():
        return jsonify(message="Key must be letters only."), 400
    elif len(key) != keysize:
        return jsonify(message="Non-matching key and key size."), 400

    keysize: int = len(key)

    # remove special characters
    # message = re.sub(r"[^a-zA-Z0-9 \n.]", "", message)
    # print(f"only letters: {message=}")

    # split message into k-length chunks
    msg_chunks: list[str] = split_to_chunks(message, isqrt(keysize))
    message = "".join(msg_chunks)

    print(f"\n{message=}")
    print(f"{key=}")
    print(f"{mode=}")
    print(f"{keysize=}")

    print(f"{msg_chunks=}")

    # column vector representation of the chunks, in letters
    msg_chunk_char_vectors: list[ColumnVector[np.str_]] = [
        mu.column_vector(chunk) for chunk in msg_chunks
    ]
    print(f"{msg_chunk_char_vectors=}")

    # convert the letters in the chunks into alphabet indices
    msg_num_chunks: list[list[int]] = [
        [mu.index_c(c) for c in chunk] for chunk in msg_chunks
    ]
    print(f"{msg_num_chunks=}")

    # column vector representation of the chunks, in indices
    msg_chunk_num_vectors: list[ColumnVector[np.int_]] = [
        mu.column_vector(chunk) for chunk in msg_num_chunks
    ]
    print(f"{msg_chunk_num_vectors=}")

    key_matrix: Matrix[np.int_] = mu.square_matrix_from_str(key)
    print(f"{key_matrix=}")

    if mode == "decrypt":
        # use the inverse to decrypt
        det = mu.det(key_matrix) % 26
        print(f"{det=}")

        modinv = sp.mod_inverse(det, 26)
        print(f"{modinv=}")

        adjugate: sp.Matrix = (
            sp.Matrix(key_matrix).adjugate().applyfunc(lambda x: (x + 26) % 26)
        )
        print(f"{adjugate=}")

        key_matrix = modinv * adjugate % 26
        print(f"inverse_key_matrix={key_matrix}")

    elif not mu.is_invertible(key_matrix):
        # example non-invertible matrix: np.array([[9, 6], [12, 8]])
        return jsonify(message="Key matrix is not invertible."), 400

    dot_products: list[ColumnVector[np.int_]] = [
        np.dot(key_matrix, vectors) for vectors in msg_chunk_num_vectors
    ]
    print(f"{dot_products=}")

    products_modulos: list[ColumnVector[np.int_]] = [
        product % 26 for product in dot_products
    ]
    print(f"{products_modulos=}")

    output_chunks = [mu.str_from_ndarray(vector) for vector in products_modulos]
    print(f"{output_chunks=}")

    output_chunk_char_vectors = [mu.column_vector(chunk) for chunk in output_chunks]

    output = "".join(output_chunks)
    print(f"{output=}\n")

    response = {
        "parameters": {"message": message, "key": key, "k": keysize},
        "key_matrix": mu.np_to_latex(key_matrix),
        "message_chunks": msg_chunks,
        "message_chunk_vectors": [
            mu.np_to_latex(vector) for vector in msg_chunk_char_vectors
        ],
        "message_chunk_num_vectors": [
            mu.np_to_latex(vector) for vector in msg_chunk_num_vectors
        ],
        "key_vector_dot_products": [
            mu.np_to_latex(dot_product) for dot_product in dot_products
        ],
        "product_modulos": [mu.np_to_latex(modulo) for modulo in products_modulos],
        "output_chunk_char_vectors": [
            mu.np_to_latex(vector) for vector in output_chunk_char_vectors
        ],
        "output_char_chunks": output_chunks,
        "output": output,
    }

    session["hill_cipher_response"] = response

    return jsonify(response)


@bp.route("/render-subtemplate")
def render_subtemplate():
    response = session.get("hill_cipher_response", {})
    session.pop("hill_cipher_response", None)
    return render_template("learn/_hill-cipher.html", **response)


@bp.app_template_filter()
def nptl(nparray: np.ndarray):
    return mu.np_to_latex(nparray)


@bp.app_template_filter()
def join(latexes: list[str], sep=","):
    return sep.join(latexes)


def split_to_chunks(text: str, chunk_len: int, placeholder: str = "X") -> list[str]:
    chunks = []

    for i in range(0, len(text), chunk_len):
        chunk = text[i : i + chunk_len]

        if len(chunk) < chunk_len:
            missing_chars = chunk_len - len(chunk)
            chunk += placeholder * missing_chars
        chunks.append(chunk)

    return chunks

app/main/__init__.py
from flask import Blueprint

bp = Blueprint("main", __name__)

from app.main import routes

app/main/routes.py
from flask import render_template

from app.main import bp


@bp.route("/", methods=["GET", "POST"])
@bp.route("/index", methods=["GET", "POST"])
def index():
    return render_template("index.html")


@bp.route("/invertible-matrix", methods=["GET", "POST"])
def invertible_matrix():
    return render_template("learn/invertible-matrix.html")

app/templates/ciphers/.example.html
{% extends "ciphers/_ciphers_template.html" %}

{% block title %}
    Title
{% endblock title %}

{% block header %}
    <h1 class="text-center">Header</h1>
{% endblock header %}

{% block desc %}
    <p class="justify">Description</p>
{% endblock desc %}

{% block input %}
    {% include "components/inputTextBox.html" %}
{% endblock input %}

{% block keys %}
    <input type="number" />
{% endblock keys %}

{% block buttons %}
    {% include "components/copyBtn.html" %}
    {% include "components/encryptDecryptBtns.html" %}
{% endblock buttons %}

{% block output %}
    {% include "components/outputTextBox.html" %}
{% endblock output %}

app/templates/ciphers/_ciphers_template.html
{% extends "layout.html" %}

{% block title %}
{% endblock title %}

{% block content %}

    <style>
        hr {
            margin-top: 2.5rem;
            margin-bottom: 2.5rem;
        }
    </style>

    {% block style %}
    {% endblock style %}

    <div class="container mt-4" id="{{ cipher_endpoint }}">
        <div id="header">
            {% block header %}
            {% endblock header %}
        </div>

        <div id="desc">
            {% block desc %}
            {% endblock desc %}
        </div>

        <hr />

        <div id="input" class="mt-3 mb-3">
            {% block input %}
            {% endblock input %}
        </div>

        <div id="keys" class="mt-3 mb-3">
            {% block keys %}
            {% endblock keys %}
        </div>

        <div id="buttons" class="mt-3 mb-3">
            {% block buttons %}
                {% include "components/copyBtn.html" %}
                {% include "components/encryptDecryptBtn.html" %}
            {% endblock buttons %}
        </div>

        <div id="output" class="mt-3 mb-3">
            {% block output %}
            {% endblock output %}
        </div>

        {% block learn_section %}
            <div id="learn-section" class="mb-4"></div>
        {% endblock learn_section %}
    </div>

    {% include "learn/__output_data.html" %}

    {% block scripts %}
    {% endblock scripts %}

    <script type ="text/javascript" src="{{ url_for('static', filename='js/encipherment.js')}}" defer></script>

{% endblock content %}

app/templates/ciphers/atbash_cipher.html
{% extends "ciphers/_ciphers_template.html" %}

{% block title %}
    Atbash
{% endblock title %}

{% block header %}
    <h1 class="text-center">Atbash Cipher</h1>
{% endblock header %}

{% block desc %}
    <p class="justify">
        The Atbash Cipher is a simple monoalphabetic substitution cipher that replaces each letter with its reverse counterpart in the alphabet.
        It is one of the oldest known ciphers, dating back to ancient Hebrew encryption techniques.
        Unlike more complex encryption methods, Atbash does not require a key — encryption and decryption follow the same process.
    </p>
{% endblock desc %}

{% block input %}
    {% include "components/inputTextBox.html" %}
{% endblock input %}

{% block buttons %}
    {% include "components/copyBtn.html" %}
    {% include "components/cipherBtn.html" %}
{% endblock buttons %}

{% block output %}
    {% include "components/outputTextBox.html" %}
{% endblock output %}

app/templates/ciphers/caesar_cipher.html
{% extends "ciphers/_ciphers_template.html" %}

{% block title %}
    Caesar Cipher
{% endblock title %}

{% block header %}
    <h1 class="text-center">Ceasar Cipher</h1>
{% endblock header %}

{% block desc %}
    <p class="justify">
        The Caesar cipher is one of the simplest and most well-known encryption techniques. It's a type of substitution cipher where each letter in the plaintext is shifted a certain number of places down or up the alphabet.
    </p>
    <p class="justify">
        It is named after Julius Caesar, who reportedly used it to protect his military communications. The Caesar cipher operates with a fixed shift value, meaning the same shift is applied to every letter in the message. While it’s easy to understand and implement, it’s also quite easy to break, making it more of a learning tool than a secure encryption method in modern times.
    </p>
{% endblock desc %}

{% block input %}
    {% include "components/inputTextBox.html" %}
{% endblock input %}

{% block keys %}
    <div class="row align-items-center">
        <div class="col-lg-3">
            <label for="shift">Shift Number:</label>
        </div>
        <div class="col">
            <input name="shift" class="key-field form-control" type="text" autocapitalize="on" />
            <div id="error-shift" class="invalid-feedback">Input is not a valid integer.</div>
        </div>
    </div>
{% endblock keys %}

{% block buttons %}
    {% include "components/copyBtn.html" %}
    {% include "components/cipherBtn.html" %}
{% endblock buttons %}

{% block output %}
    {% include "components/outputTextBox.html" %}
{% endblock output %}

app/templates/ciphers/hill-cipher.html
{% extends "ciphers/_ciphers_template.html" %}

{% block title %}
    Hill Cipher
{% endblock title %}

{% block style %}
    <style>
        input[name="key"] {
            text-transform: uppercase;
        }
    </style>
{% endblock style %}

{% block header %}
    <h1 class="text-center">Hill Cipher Cryptography</h1>
{% endblock header %}

{% block desc %}
    <p class="justify">
        The Hill cipher is a polygraphic substitution cipher that encrypts text by matrix multiplication. It was devised by Lester Hill in 1929, making it one of the first linear algebra-based encryption systems.
    </p>

    <p class="justify">
        This cipher encrypts letters as blocks rather than individually. A key matrix (a square matrix) is used to convert plaintext to ciphertext using modular arithmetic. To decrypt, the inverted key matrix is utilized.
    </p>
{% endblock desc %}

{% block input %}
    {% include "components/inputTextBox.html" %}
{% endblock input %}

{% block keys %}
    <div class="row align-items-center">
        <div class="col-lg-3">
            <label for="key">Custom key:</label>
        </div>
        <div class="col-lg-3">
            <input type="radio" id="btn-2x2" name="keysize" value="4" checked="true" />
            <label for="btn-2x2" class="me-4">$2 \times 2$</label>
            <input type="radio" id="btn-3x3" name="keysize" value="9" />
            <label for="btn-3x3">$3 \times 3$</label>
        </div>
        <div class="col">
            <input name="key" class="key-field form-control" type="text" autocapitalize="on" />
            <div id="error-key" class="invalid-feedback">Key matrix is not invertible.</div>
        </div>
    </div>
{% endblock keys %}

{% block output %}
    {% include "components/outputTextBox.html" %}
{% endblock output %}

{% block script %}
    <script>
        $(function() {
            function setMaxLength() {
                var maxlength = $("input[name='keysize']:checked").val();
                $("#key-field").attr("maxlength", maxlength);
            }

            setMaxLength();

            $("input[name='keysize']").on("change", setMaxLength);
        });
    </script>
{% endblock script %}

app/templates/ciphers/rsa.html
{% extends "ciphers/_ciphers_template.html" %}

{% block title %}
    RSA
{% endblock title %}

{% block header %}
    <h1 class="text-center">RSA Cryptography</h1>
{% endblock header %}

{% block desc %}
    <p class="text-muted">
        Disclaimer: This page is for educational purposes only. Never use the tool on this page for actual security-sensitive activities.
        This tool expects plaintext, but RSA is designed for positive integers only. The plaintext is converted to a number.
    </p>

    <p>
        RSA (Rivest-Shamir-Adleman) is a popular public-key cryptographic technique for
        safe data encryption and deciphering. It relies on the mathematical difficulty
        of factoring large prime numbers, which makes it highly secure. RSA utilizes two keys:
    </p>

    <ul>
        <li>A public key for encryption.</li>
        <li>A private key for decryption.</li>
    </ul>

    <p>
        This ensures that no matter how an attacker intercepts the encrypted message,
        they are unable to decrypt it without the private key.
    </p>
{% endblock desc %}

{% block input %}
    {% include "components/inputTextBox.html" %}
{% endblock input %}

{% block keys %}
    <h3>Custom Keys</h3>

    <div class="row">
        <h6 class="subtext">
            Input two large prime numbers $p$ and $q$ and encryption exponent $e$, or leave them empty to generate values for you.
        </h6>
    </div>

    <div class="row">
        <div class="col">
            <label for="p">Prime $p$:</label>
            <input name="p" type="text" id="p" class="key-field form-control" />
            <div id="error-p" class="invalid-feedback">Error.</div>
        </div>

        <div class="col">
            <label for="q">Prime $q$:</label>
            <input name="q" type="text" id="q" class="key-field form-control" />
            <div id="error-q" class="invalid-feedback">Error.</div>
        </div>

        <div class="col">
            <label for="e">Exponent $e$:</label>
            <input name="e" type="text" id="e" class="key-field form-control" />
            <div id="error-e" class="invalid-feedback">Error.</div>
        </div>

        <div class="row">
            <button class="btn btn-warning w-25 mt-3 ms-3" type="button" id="rsa-generate-keys-btn">
                Generate
            </button>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <label for="public-key">Public key $(n, e)$:</label>
            <input name="public-key" class="key-field form-control" readonly />
        </div>

        <div class="col">
            <label for="private-key">Private key $(n, d)$:</label>
            <input name="private-key" class="key-field form-control" readonly />
        </div>
    </div>
{% endblock keys %}

{% block output %}
    {% include "components/outputTextBox.html" %}
{% endblock output %}

app/templates/ciphers/vigenere_cipher.html
{% extends "ciphers/_ciphers_template.html" %}

{% block title %}
    Vigenère Cipher
{% endblock title %}

{% block header %}
    <h1 class="text-center">Vigenère Cipher</h1>
{% endblock header %}

{% block desc %}
    <p class="justify">
        The Vigenère Cipher is a method of encrypting alphabetic text by using a series of interwoven Caesar ciphers based on the letters of a keyword. It was first described in the 16th century and became widely known as a secure cipher for centuries.
    </p>
    <p class="justify">
        Unlike the simple <a href="{{ url_for('ciphers.caesar_cipher_view') }}">Caesar Cipher</a> , which shifts every letter by the same amount, the Vigenère Cipher uses a different shift for each letter, making it more resistant to frequency analysis. This cipher works by aligning a repeating keyword with the plaintext and shifting each letter based on the corresponding key letter. It's an excellent example of a polyalphabetic cipher and is often used in educational settings to demonstrate the basics of cryptography.
    </p>
{% endblock desc %}

{% block input %}
    {% include "components/inputTextBox.html" %}
{% endblock input %}

{% block keys %}
    <div class="row align-items-center">
        <div class="col-lg-3">
            <label for="key">Key:</label>
        </div>
        <div class="col">
            <input name="key" class="key-field form-control" type="text" autocapitalize="on" />
            <div id="error-key" class="invalid-feedback">Input is not a valid integer.</div>
        </div>
    </div>
{% endblock keys %}

{% block buttons %}
    {% include "components/copyBtn.html" %}
    {% include "components/encryptDecryptBtn.html" %}
{% endblock buttons %}

{% block output %}
    {% include "components/outputTextBox.html" %}
{% endblock output %}

app/templates/components/alphabetIndexTable.html
{% set alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ" %}

<div class="table-responsive">
    <table class="table table-striped">
        <tr>
            <th>Letter</th>
            {% for letter in alphabet %}<td>{{ letter }}</td>{% endfor %}
        </tr>
        <tr>
            <th>Number</th>
            {% for i in range(0, alphabet | length) %}<td>{{ i }}</td>{% endfor %}
        </tr>
    </table>
</div>

app/templates/components/cipherBtn.html
<div class="float-end">
    <button class="btn btn-warning cipher-btn" id="cipher-btn">Cipher</button>
</div>

app/templates/components/copyBtn.html
<button class="btn btn-warning copy-btn">Copy output to input</button>

app/templates/components/encryptDecryptBtn.html
<div class="float-end">
    <button class="btn btn-warning cipher-btn" id="encrypt-btn" data-mode="encrypt">Encrypt</button>
    <button class="btn btn-warning cipher-btn" id="decrypt-btn" data-mode="decrypt">Decrypt</button>
</div>

app/templates/components/inputTextBox.html
<label for="message-field">Input textbox:</label>
<textarea name="message-field" class="message-field form-control mb-4" autocapitalize="on"></textarea>

app/templates/components/outputTextBox.html
<textarea name="output-field"
          class="output-field form-control mb-4"
          placeholder="Output goes here..."
          readonly
          autocapitalize="on"></textarea>

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <title>
            {% block title %}
                Home Page
            {% endblock title %}
        </title>

        <link rel="shortcut icon"
              href="{{ url_for('static', filename='img/encrypted.png') }}"
              type="image/x-icon" />

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
              crossorigin="anonymous" />

        <script type="text/javascript" defer src="{{ url_for('static', filename='js/mathjax-config.js') }}"></script>
        <script type="text/javascript"
                id="MathJax-script"
                defer
                src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

        <script src="https://code.jquery.com/jquery-3.7.1.min.js"
                integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
                crossorigin="anonymous"></script>

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400..900&display=swap"
              rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Orbitron:wght@400..900&display=swap"
              rel="stylesheet" />

        <link href="{{ url_for('static', filename='css/styles.scss.css') }}" rel="stylesheet" type="text/css" />
    </head>

    <body>
        <header class="d-flex flex-wrap justify-content-center py-3">
            <div class="container">
                <a class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none"
                   href="{{ url_for('main.index') }}">
                    <img class="bi me-2"
                         src="{{ url_for('static', filename='img/encrypted.png') }}"
                         alt="FieldSecure"
                         id="logo" />
                    <span class="p-2 text-white" id="title">FieldSecure</span>
                </a>
            </div>
        </header>

        <main>
            {% block content %}
            {% endblock content %}
        </main>

        <footer>
            <div class="container mt-4">
                <p class="text-center mt-4">© 2025 quint</p>
            </div>
        </footer>
    </body>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"></script>

    {% block script %}

    {% endblock script %}
</html>

app/templates/learn/__output_data.html
<div id="output-data" data-output="{{ output }}"></div>

app/templates/learn/_atbash_cipher.html
<h2>Encryption and Decryption</h2>
<p>
    Since Atbash is a simple substitution cipher, the encryption and decryption processes are identical.
</p>

<h3>Step 1:</h3>
<p>
    Define the alphabet mapping. Each letter in the alphabet is replaced with its reverse counterpart.
</p>

{% set alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ" %}

<div class="table-responsive">
    <table class="table table-striped">
        <tr>
            <th>Plaintext</th>
            {% for letter in alphabet %}<td>{{ letter }}</td>{% endfor %}
        </tr>
        <tr>
            <th>Ciphertext</th>
            {% for letter in alphabet | reverse %}<td>{{ letter }}</td>{% endfor %}
        </tr>
    </table>
</div>

<h3>Step 2:</h3>
<p>
    Convert each letter in the message. For each letter in the input message, replace it with its corresponding letter from the reversed alphabet.
</p>

<div class="step">
    $$\text{For plaintext "{{ message | tex_escape }}":}$$
    $$$$
    {% for c, r in zip(message, output) %}
        {% if c is lower or c is upper %}$$ {{ c }} \rightarrow {{ r }}$${% endif %}
    {% endfor %}
</div>

<h3>Step 3:</h3>
<p>Merge the mapped letters, keeping special characters intact, to get the encrypted message.</p>

<div class="step">$${{ output | tex_escape }}$$</div>

{% include "learn/__output_data.html" %}

app/templates/learn/_hill-cipher.html
<h1>Key Generation</h1>

<h2>Step 1:</h2>
<p>
    Replace each letter in the key by its index in the alphabet $i \pmod{26}$ and create a square matrix $K_{n \times n}$ from the values.
</p>

{% include "components/alphabetIndexTable.html" %}

<p>With key ${{ key }}$,</p>

<div class="step">
    $$ {{ key }} \to {{ key_matrix }} $$
    then,
    $$ K = {{ key_matrix }} $$
</div>

<h2>Step 2:</h2>
<p>
    Ensure that the inverse operation applies on the key matrix $K_{n x n} \pmod{26}$, i.e. $K$ has an <a href="{{ url_for('main.invertible_matrix') }}">invertible matrix</a> $K^{-1}$.
</p>

{% if mode == "encrypt" %}

    <h1 class="mt-4">Encryption</h1>

    <h2>Step 1:</h2>
    <p>Clean the message by removing non-alphabetic characters.</p>

    <div class="step">
        $$ {{ original_message | tex_escape }} $$
        $$ \downarrow $$
        $$ {{ message | tex_escape }} $$
    </div>

    <h2>Step 2:</h2>
    <p>
        Create a series of $1 \times n$ matrices, where $n$ is derived from the key matrix $K_{n \times n}$. This requires the length of the message should be a multiple of $n$, otherwise fill the missing length with a placeholder character, usually $X$.
    </p>

    <div class="step">
        $$ {{ message | tex_escape }} $$
        $$ \downarrow $$
        $$ {{ message_chunk_vectors | join }} $$
    </div>

    <p>Convert each letter in the mesage using the same process as the key matrix generation.</p>

    <div class="step">
        $$ {{ message_chunk_vectors | join }} $$
        $$ \downarrow $$
        $$ {{ message_chunk_num_vectors | join }} $$
    </div>

    <h2>Step 3:</h2>
    <p>Multiply each column with the key matrix $K \pmod{26}$.</p>

    <div class="step">
        {% for (vector, modulo) in zip(message_chunk_num_vectors, product_modulos) %}
            $$ {{ key_matrix }} {{ vector }} = {{ modulo }} \pmod{26} $$
        {% endfor %}
    </div>

    <h2>Step 4:</h2>
    <p>
        Use the products $\pmod{26}$ as indices in the alphabet to produce letters, respecting capitalization.
    </p>

    <div class="step">
        $${{ product_modulos | join }} $$
        $$ \downarrow $$
        $$ {{ output_chunk_char_vectors | join }} $$
    </div>

    <h2>Step 5:</h2>
    <p>Join the letters into one string to get the output.</p>

    <div class="step">$${{ output | tex_escape }}$$</div>

{% else %}

    <h1 class="mt-4">Decryption</h1>

    <h2>Step 1:</h2>
    <p>Compute the inverse of the key matrix $K^{-1} \mod(26)$.</p>

    <div class="step">
        $$ K = {{ key_matrix }} $$
        $$\text{then}$$
        $$K^{-1} \pmod{26} = {{ inv_key_matrix }}$$
    </div>

    <h2>Step 2:</h2>
    <p>Multiply each column with the key matrix $K \pmod{26}$.</p>

    <div class="step">
        {% for (vector, modulo) in zip(message_chunk_num_vectors, product_modulos) %}
            $$ {{ inv_key_matrix }} {{ vector }} = {{ modulo }} \pmod{26} $$
        {% endfor %}
    </div>

    <h2>Step 3:</h2>
    <p>Use the products $\pmod{26}$ as indices in the alphabet to produce letters.</p>

    <div class="step">
        $${{ product_modulos | join }} $$
        $$ \downarrow $$
        $$ {{ output_chunk_char_vectors | join }} $$
    </div>

    <h2>Step 4:</h2>
    <p>Join the letters into one string to get the original plaintext.</p>

    <div class="step">$${{ output | tex_escape }}$$</div>
{% endif %}

{% include "learn/__output_data.html" %}

templates/encrypt.html
{% extends "layout.html" %}

{% block title %}
    Encrypt/Decrypt
{% endblock title %}

{% block content %}
    <h1>Hello, World!</h1>
{% endblock content %}